#include "DataFormats/Common/interface/DeviceProduct.h"
#include "DataFormats/Common/interface/Wrapper.h"
#include "DataFormats/PortableVertex/interface/VertexSoA.h"
#include "DataFormats/PortableVertex/interface/alpaka/VertexDeviceCollection.h"
#include "DataFormats/PortableVertex/interface/TrackForVertexSoA.h"
#include "DataFormats/PortableVertex/interface/alpaka/TrackForVertexDeviceCollection.h"
