#include "DataFormats/Common/interface/Wrapper.h"
#include "DataFormats/PortableVertex/interface/VertexHostCollection.h"
#include "DataFormats/PortableVertex/interface/VertexSoA.h"
#include "DataFormats/PortableVertex/interface/TrackForVertexHostCollection.h"
#include "DataFormats/PortableVertex/interface/TrackForVertexSoA.h"
